import * as XLSX from 'xlsx';

export function exportFormulaToExcel(formula: string, filename: string = 'XL-Architect-Formula.xlsx') {
  try {
    // Create a new workbook
    const wb = XLSX.utils.book_new();
    
    // Create data for the sheet
    const wsData = [
      ['Type', 'Content', 'Source'],
      ['Excel Formula', formula, 'Generated by XL-Architect AI']
    ];
    
    const ws = XLSX.utils.aoa_to_sheet(wsData);
    
    // Set column widths for better readability
    const wscols = [
      { wch: 15 }, // Type
      { wch: 60 }, // Content
      { wch: 30 }  // Source
    ];
    ws['!cols'] = wscols;
    
    // Add the worksheet to the workbook
    XLSX.utils.book_append_sheet(wb, ws, 'Formula');
    
    // Export the file using a more robust method for browser environments
    const wbout = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
    const blob = new Blob([wbout], { type: 'application/octet-stream' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename.endsWith('.xlsx') ? filename : `${filename}.xlsx`;
    document.body.appendChild(a);
    a.click();
    
    // Cleanup
    setTimeout(() => {
      document.body.removeChild(a);
      window.URL.revokeObjectURL(url);
    }, 100);
  } catch (error) {
    console.error('Excel Export Error:', error);
  }
}
