import { useState, useRef, useEffect, type FormEvent } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  Search, 
  Command, 
  Keyboard, 
  MousePointer2, 
  BarChart3, 
  Lightbulb, 
  History, 
  Cpu, 
  ArrowRight,
  Loader2,
  FileSpreadsheet,
  X,
  Menu,
  BookOpen,
  Download,
  Bug,
  Layers,
  CheckCircle2,
  Palette,
  Sun,
  Moon,
  ChevronRight,
  Fingerprint,
  Activity,
  Box,
  Bookmark,
  Copy,
  ExternalLink
} from 'lucide-react';
import { getExcelGuidance, type ExcelSolution } from './services/gemini';
import ShortcutGuide from './components/ShortcutGuide';
import FormulaDebugger from './components/FormulaDebugger';
import SavedTemplates from './components/SavedTemplates';
import FormattingGuide from './components/FormattingGuide';
import { ModalOverlay, ClearButton, CopyButton } from './components/Common';
import { saveTemplate } from './data/templates';
import { exportFormulaToExcel } from './lib/excelExport';

type AppView = 'architect' | 'shortcuts' | 'debugger' | 'templates' | 'formatting';

export default function App() {
  const [view, setView] = useState<AppView>('architect');
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const [theme, setTheme] = useState<'light' | 'dark'>(() => {
    if (typeof window !== 'undefined') {
      return localStorage.getItem('xl_theme') as 'light' | 'dark' || 'light';
    }
    return 'light';
  });
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const [solution, setSolution] = useState<ExcelSolution | null>(null);
  const [history, setHistory] = useState<ExcelSolution[]>([]);
  const [saveStatus, setSaveStatus] = useState<string | null>(null);
  const [debugTarget, setDebugTarget] = useState<string>('');
  const inputRef = useRef<HTMLInputElement>(null);
  const scrollRef = useRef<HTMLDivElement>(null);

  const handleQuickChip = (label: string) => {
    setInput(label);
    // Use a small timeout to allow state to update before submitting
    setTimeout(() => {
      handleSubmit();
    }, 0);
  };

  const handleSaveTemplate = () => {
    if (!solution?.visualization) return;
    saveTemplate({
      name: solution.goal,
      suggestedType: solution.visualization.suggestedType,
      setupGuidance: solution.visualization.setupGuidance,
      designTip: solution.visualization.designTip,
    });
    setSaveStatus('Archived');
    setTimeout(() => setSaveStatus(null), 3000);
  };

  const handleDownload = () => {
    if (!solution) return;

    const markdown = `# XL-Architect Blueprint: ${solution.goal}

## 🎯 Primary Objective
${solution.goal}

## ⚙️ Engineered Formula
\`\`\`excel
${solution.solution}
\`\`\`

## 🧠 Logic Breakdown
${solution.humanReadableLogic}

${solution.dataRequirement ? `## 📋 Data Requirements\n${solution.dataRequirement}\n` : ''}

## 🖱️ Navigation Steps
${solution.navigationSteps.map((step, i) => `${i + 1}. ${step}`).join('\n')}

## ⌨️ Keyboard Shortcuts
- **Windows:** ${solution.shortcuts.windows}
- **macOS:** ${solution.shortcuts.mac}

## 📊 Visualization Guide
${solution.visualization ? `
- **Chart Type:** ${solution.visualization.suggestedType}
- **Why:** ${solution.visualization.why}
- **Setup Guidance:**
${solution.visualization.setupGuidance}
- **Design Tip:** ${solution.visualization.designTip}
` : 'No visualization suggested for this solution.'}

## 💡 Pro Tip
${solution.proTip}

---
*Generated by XL-Architect & Gemini AI*
`;

    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `excel-blueprint-${solution.goal.toLowerCase().replace(/\s+/g, '-')}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleSubmit = async (e?: FormEvent) => {
    if (e) e.preventDefault();
    const targetInput = input.trim();
    if (!targetInput || loading) return;

    setLoading(true);
    try {
      const result = await getExcelGuidance(targetInput);
      setSolution(result);
      setHistory(prev => [result, ...prev.slice(0, 4)]);
      setInput('');
    } catch (error) {
      console.error('Error fetching guidance:', error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (solution && scrollRef.current && view === 'architect') {
      scrollRef.current.scrollIntoView({ behavior: 'smooth' });
    }
  }, [solution, view]);

  useEffect(() => {
    const root = window.document.documentElement;
    if (theme === 'dark') {
      root.classList.add('dark');
    } else {
      root.classList.remove('dark');
    }
    localStorage.setItem('xl_theme', theme);
  }, [theme]);

  const toggleTheme = () => setTheme(prev => prev === 'light' ? 'dark' : 'light');

  return (
    <div className={`min-h-screen font-sans selection:bg-[#217346] selection:text-white transition-colors duration-500 ${theme === 'dark' ? 'dark bg-slate-950 text-slate-100' : 'bg-[#F3F4F6] text-slate-900'}`}>
      {/* Background Grid Pattern */}
      <div className="fixed inset-0 pointer-events-none opacity-5 dark:opacity-[0.03] grayscale" 
           style={{ backgroundImage: 'linear-gradient(#217346 1px, transparent 1px), linear-gradient(90deg, #217346 1px, transparent 1px)', backgroundSize: '40px 40px' }} 
      />

      {/* Header */}
      <header className="sticky top-0 z-50 bg-white/80 dark:bg-slate-900/80 backdrop-blur-md border-b border-slate-200 dark:border-slate-800 px-4 md:px-6 py-4 flex items-center justify-between shadow-sm">
        <div className="flex items-center gap-2 md:gap-3">
          <div className="bg-[#217346] p-2 rounded-lg shadow-lg shadow-[#217346]/20 cursor-pointer" onClick={() => { setView('architect'); setIsMenuOpen(false); }}>
            <Cpu className="w-5 h-5 md:w-6 md:h-6 text-white" />
          </div>
          <div>
            <h1 className="text-lg md:text-xl font-bold tracking-tight text-slate-800 dark:text-white leading-none">XL-ARCHITECT</h1>
            <p className="text-[8px] md:text-[10px] font-mono uppercase tracking-[0.2em] text-[#217346] dark:text-[#28a162] font-bold">World Class Excel Intelligence</p>
          </div>
        </div>
        
        <div className="flex items-center gap-2 md:gap-4">
          {/* Desktop Navigation */}
          <div className="hidden lg:flex items-center gap-1 bg-slate-100 dark:bg-slate-800 p-1 rounded-xl mr-2">
            {[
              { id: 'architect', label: 'Architect', icon: Command },
              { id: 'shortcuts', label: 'Repository', icon: Keyboard },
              { id: 'debugger', label: 'Debugger', icon: Bug },
              { id: 'templates', label: 'Templates', icon: Layers },
              { id: 'formatting', label: 'Conditioning', icon: Palette }
            ].map((nav) => (
              <button 
                key={nav.id}
                onClick={() => setView(nav.id as AppView)}
                className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all flex items-center gap-2 ${view === nav.id ? 'bg-white dark:bg-slate-700 shadow-sm text-[#217346] dark:text-white' : 'text-slate-400 hover:text-slate-600 dark:text-slate-500'}`}
              >
                <nav.icon className="w-3.5 h-3.5" />
                {nav.label}
              </button>
            ))}
          </div>

          <div className="flex items-center gap-2">
            <button 
              onClick={toggleTheme}
              className="p-2 rounded-xl bg-slate-100 dark:bg-slate-800 text-slate-500 dark:text-slate-400 hover:text-[#217346] dark:hover:text-green-500 transition-all border border-slate-200 dark:border-slate-700 shadow-sm"
              aria-label="Toggle Theme"
            >
              {theme === 'light' ? <Moon className="w-4 h-4 text-slate-600" /> : <Sun className="w-4 h-4 text-yellow-400" />}
            </button>
            
            {/* Hamburger Menu Trigger */}
            <button
              onClick={() => setIsMenuOpen(!isMenuOpen)}
              className="lg:hidden p-2 rounded-xl bg-slate-100 dark:bg-slate-800 text-slate-500 dark:text-slate-400 hover:text-[#217346] dark:hover:text-green-500 transition-all border border-slate-200 dark:border-slate-700 shadow-sm"
              aria-label="Toggle Mobile Menu"
            >
              {isMenuOpen ? <X className="w-5 h-5" /> : <Menu className="w-5 h-5" />}
            </button>
          </div>
        </div>
      </header>

      {/* Mobile Navigation Menu */}
      <AnimatePresence>
        {isMenuOpen && (
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: 'auto' }}
            exit={{ opacity: 0, height: 0 }}
            className="lg:hidden sticky top-[73px] z-[45] bg-white dark:bg-slate-900 border-b border-slate-200 dark:border-slate-800 shadow-xl overflow-hidden"
          >
            <div className="p-4 grid grid-cols-2 gap-2">
              {[
                { id: 'architect', label: 'Architect', icon: Command, color: 'bg-green-50 dark:bg-green-950/30' },
                { id: 'shortcuts', label: 'Repository', icon: Keyboard, color: 'bg-blue-50 dark:bg-blue-950/30' },
                { id: 'debugger', label: 'Debugger', icon: Bug, color: 'bg-red-50 dark:bg-red-950/30' },
                { id: 'templates', label: 'Templates', icon: Layers, color: 'bg-emerald-50 dark:bg-emerald-950/30' },
                { id: 'formatting', label: 'Conditioning', icon: Palette, color: 'bg-indigo-50 dark:bg-indigo-950/30' }
              ].map((nav) => (
                <button
                  key={nav.id}
                  onClick={() => {
                    setView(nav.id as AppView);
                    setIsMenuOpen(false);
                  }}
                  className={`flex flex-col items-center justify-center p-4 rounded-2xl border-2 transition-all gap-2 ${view === nav.id ? 'border-[#217346] bg-[#217346]/10 text-[#217346] dark:text-green-400' : 'border-slate-100 dark:border-slate-800 text-slate-600 dark:text-slate-400 hover:border-slate-200 dark:hover:border-slate-700'}`}
                >
                  <nav.icon className="w-5 h-5" />
                  <span className="text-[10px] font-bold uppercase tracking-widest">{nav.label}</span>
                </button>
              ))}
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      <main className="max-w-4xl mx-auto px-6 py-12 relative z-10">
        <AnimatePresence mode="wait">
          {view === 'architect' && (
            <motion.div
              key="architect-view"
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: 20 }}
              className="w-full"
            >
              {/* Breadcrumb Trail */}
              {(input || solution || loading) && (
                <div className="max-w-4xl mx-auto mb-12 flex items-center justify-center gap-4 md:gap-8 overflow-x-auto no-scrollbar py-2">
                  <div className={`flex items-center gap-2 transition-all ${input || solution || loading ? 'text-[#217346] dark:text-green-500 opacity-100' : 'text-slate-300 dark:text-slate-700 opacity-50'}`}>
                    <div className={`w-8 h-8 rounded-full flex items-center justify-center border-2 ${input ? 'bg-[#217346] dark:bg-[#28a162] text-white border-[#217346] dark:border-[#28a162]' : 'border-slate-200 dark:border-slate-800 text-slate-400 dark:text-slate-500'}`}>
                      <Fingerprint className="w-4 h-4" />
                    </div>
                    <span className="text-[10px] font-black uppercase tracking-widest hidden sm:inline">Requirement</span>
                  </div>
                  <ChevronRight className="w-4 h-4 text-slate-300 dark:text-slate-800" />
                  
                  <div className={`flex items-center gap-2 transition-all ${loading || solution ? 'text-[#217346] dark:text-green-500 opacity-100' : 'text-slate-300 dark:text-slate-700 opacity-50'}`}>
                    <div className={`w-8 h-8 rounded-full flex items-center justify-center border-2 ${loading ? 'bg-[#217346] dark:bg-[#28a162] text-white border-[#217346] dark:border-[#28a162] animate-pulse' : (solution ? 'bg-[#217346] dark:bg-[#28a162] text-white border-[#217346] dark:border-[#28a162]' : 'border-slate-200 dark:border-slate-800 text-slate-400 dark:text-slate-500')}`}>
                      <Activity className="w-4 h-4" />
                    </div>
                    <span className="text-[10px] font-black uppercase tracking-widest hidden sm:inline">Diagnostics</span>
                  </div>
                  <ChevronRight className="w-4 h-4 text-slate-300 dark:text-slate-800" />
 
                  <div className={`flex items-center gap-2 transition-all ${solution ? 'text-[#217346] dark:text-green-500 opacity-100' : 'text-slate-300 dark:text-slate-700 opacity-50'}`}>
                    <div className={`w-8 h-8 rounded-full flex items-center justify-center border-2 ${solution ? 'bg-[#217346] dark:bg-[#28a162] text-white border-[#217346] dark:border-[#28a162]' : 'border-slate-200 dark:border-slate-800 text-slate-400 dark:text-slate-500'}`}>
                      <Box className="w-4 h-4" />
                    </div>
                    <span className="text-[10px] font-black uppercase tracking-widest hidden sm:inline">Blueprint</span>
                  </div>
                </div>
              )}

              {/* Intro Section */}
              <AnimatePresence mode="wait">
                {!solution && !loading && (
                  <motion.div 
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, scale: 0.95 }}
                    className="text-center mb-12"
                  >
                    <h2 className="text-4xl md:text-5xl font-black text-slate-900 dark:text-white mb-4 tracking-tighter">
                      Master Excel with <span className="text-[#217346]">Precision.</span>
                    </h2>
                    <p className="text-slate-500 dark:text-slate-400 text-lg max-w-xl mx-auto leading-relaxed">
                      Describe your goal in plain English. I'll architect the formula, the navigation, and the shortcuts instantly.
                    </p>
                    <div className="mt-8 flex justify-center">
                      <button 
                        onClick={() => setView('shortcuts')}
                        className="flex items-center gap-2 text-[#217346] dark:text-green-500 font-bold text-xs uppercase tracking-[0.2em] hover:opacity-70 transition-opacity"
                      >
                        <BookOpen className="w-4 h-4" />
                        Explore Shortcut Repository
                      </button>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>

              {/* Input area */}
              <div className={`transition-all duration-500 ${solution ? 'mb-12' : 'mb-24'}`}>
                <form onSubmit={handleSubmit} className="relative group">
                  <div className="absolute inset-y-0 left-0 pl-6 flex items-center pointer-events-none">
                    <Search className="w-5 h-5 text-slate-400 group-focus-within:text-[#217346] transition-colors" />
                  </div>
                  <input
                    ref={inputRef}
                    autoFocus
                    type="text"
                    value={input}
                    onChange={(e) => setInput(e.target.value)}
                    placeholder="Describe your excel goal..."
                    className="w-full bg-white dark:bg-slate-900 border-2 border-slate-200 dark:border-slate-800 rounded-2xl py-4 md:py-6 pl-12 md:pl-14 pr-14 sm:pr-40 md:pr-48 text-base md:text-lg dark:text-white shadow-xl shadow-slate-200/50 dark:shadow-slate-950/50 focus:border-[#217346] focus:ring-0 transition-all outline-none"
                  />
                  <div className="absolute right-14 sm:right-[10.5rem] md:right-[11rem] inset-y-0 flex items-center">
                    <ClearButton 
                      isVisible={input.length > 0} 
                      onClick={() => {
                        setInput('');
                        inputRef.current?.focus();
                      }} 
                    />
                  </div>
                  <button
                    type="submit"
                    disabled={loading || !input.trim()}
                    className="absolute right-2 md:right-3 inset-y-2 md:inset-y-3 px-3 md:px-6 bg-[#217346] text-white rounded-xl font-bold flex items-center gap-2 hover:bg-[#1a5c38] transition-all disabled:opacity-50 disabled:cursor-not-allowed shadow-lg shadow-[#217346]/20 min-w-[44px] sm:min-w-[140px] justify-center"
                  >
                    {loading ? (
                      <>
                        <Loader2 className="w-4 md:w-5 h-4 md:h-5 animate-spin" />
                        <span className="hidden sm:inline">PROCESSING...</span>
                      </>
                    ) : (
                      <>
                        <ArrowRight className="w-4 md:w-5 h-4 md:h-5" />
                        <span className="hidden sm:inline">ANALYZE</span>
                      </>
                    )}
                  </button>
                </form>
                
                {/* Quick suggestions */}
                {!solution && (
                  <div className="flex flex-wrap gap-2 mt-4 justify-center">
                    {['VLOOKUP basics', 'Sales trends chart', 'Pivot table guide', 'Date calculations'].map((label) => (
                      <button
                        key={label}
                        onClick={() => handleQuickChip(label)}
                        className="px-3 py-1.5 rounded-full bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 text-xs font-medium text-slate-600 dark:text-slate-400 hover:border-[#217346] hover:text-[#217346] dark:hover:text-[#28a162] transition-all"
                      >
                        {label}
                      </button>
                    ))}
                  </div>
                )}
              </div>

              {/* Result Area */}
              <div ref={scrollRef}>
                <AnimatePresence>
                  {solution && (
                    <motion.div
                      initial={{ opacity: 0, y: 40 }}
                      animate={{ opacity: 1, y: 0 }}
                      className="space-y-8 pb-24"
                    >
                      {/* 🎯 Goal and Error Analysis */}
                      <div className="space-y-6">
                        {solution.errorAnalysis && (
                          <motion.div 
                            initial={{ opacity: 0, x: -20 }}
                            animate={{ opacity: 1, x: 0 }}
                            className="bg-red-50 dark:bg-red-950/20 border-l-4 border-red-500 p-6 rounded-r-2xl"
                          >
                            <div className="flex items-center gap-2 text-red-700 dark:text-red-400 font-bold text-xs uppercase tracking-widest mb-2">
                              <X className="w-4 h-4" />
                              Error Analysis Detected: {solution.errorAnalysis.errorCode}
                            </div>
                            <p className="text-red-900 dark:text-red-200 font-medium">
                              {solution.errorAnalysis.explanation}
                            </p>
                          </motion.div>
                        )}

                        {solution.dataRequirement && (
                          <motion.div 
                            initial={{ opacity: 0, x: -20 }}
                            animate={{ opacity: 1, x: 0 }}
                            className="bg-[#217346]/5 dark:bg-[#217346]/10 border-l-4 border-[#217346] p-6 rounded-r-2xl"
                          >
                            <div className="flex items-center gap-2 text-[#217346] dark:text-green-500 font-bold text-xs uppercase tracking-widest mb-2">
                              <FileSpreadsheet className="w-4 h-4" />
                              Data Architecture Note
                            </div>
                            <p className="text-slate-800 dark:text-slate-200 font-semibold italic">
                              {solution.dataRequirement}
                            </p>
                          </motion.div>
                        )}

                        <div className="bg-white dark:bg-slate-900 rounded-3xl p-8 shadow-xl shadow-slate-200/60 dark:shadow-slate-950/60 border border-slate-100 dark:border-slate-800 flex flex-col md:flex-row gap-8 relative overflow-hidden">
                          {/* Export Button */}
                          <div className="absolute top-4 right-4 z-20">
                            <button
                              onClick={handleDownload}
                              className="flex items-center gap-2 bg-[#217346]/5 dark:bg-[#217346]/10 text-[#217346] dark:text-green-500 px-3 py-1.5 rounded-xl text-[10px] font-bold hover:bg-[#217346] hover:text-white transition-all border border-[#217346]/10 shadow-sm"
                              title="Download Markdown Blueprint"
                            >
                              <Download className="w-3 h-3" />
                              <span className="hidden sm:inline">EXPORT BLUEPRINT</span>
                            </button>
                          </div>

                          <div className="flex-1">
                            <div className="flex items-center gap-2 text-[#217346] dark:text-green-500 font-bold text-xs uppercase tracking-widest mb-2">
                              <Command className="w-4 h-4" />
                              Goal
                            </div>
                            <h3 className="text-3xl font-bold text-slate-800 dark:text-white leading-tight">
                              {solution.goal}
                            </h3>
                          </div>
                          
                          <div className="flex-1 bg-slate-50 dark:bg-slate-800 rounded-2xl p-6 border border-slate-100 dark:border-slate-700 flex flex-col justify-center">
                            <div className="flex items-center gap-2 text-[#217346] dark:text-green-500 font-bold text-xs uppercase tracking-widest mb-3">
                              <Cpu className="w-4 h-4" />
                              Engineered Solution
                            </div>
                            <div className="relative group/formula">
                              <div className="font-mono text-xl bg-slate-900 border border-slate-800 p-4 pr-16 rounded-xl text-green-400 break-all shadow-inner overflow-x-auto selection:bg-green-500/30 min-h-[4rem] flex items-center">
                                {solution.solution}
                              </div>
                              <div className="absolute right-2 top-2 flex flex-col gap-2 opacity-100 md:opacity-0 md:group-hover/formula:opacity-100 transition-opacity">
                                <CopyButton 
                                  text={solution.solution} 
                                  className="p-2 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-lg transition-colors shadow-lg border border-slate-700 flex items-center justify-center"
                                />
                                <button
                                  onClick={() => exportFormulaToExcel(solution.solution, `Formula-${solution.goal.slice(0, 20)}.xlsx`)}
                                  className="p-2 bg-green-800 hover:bg-green-700 text-green-100 rounded-lg transition-colors shadow-lg border border-green-700 flex items-center justify-center"
                                  title="Export to Excel"
                                >
                                  <FileSpreadsheet className="w-4 h-4" />
                                </button>
                                <button
                                  onClick={() => {
                                    setDebugTarget(solution.solution);
                                    setView('debugger');
                                  }}
                                  className="p-2 bg-[#217346] hover:bg-[#1a5c38] text-white rounded-lg transition-colors shadow-lg border border-[#1a5c38] flex items-center justify-center"
                                  title="Analyze in Debugger"
                                >
                                  <ExternalLink className="w-4 h-4" />
                                </button>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>

                      {/* Grid for Steps and Shortcuts */}
                      <div className="grid md:grid-cols-2 gap-8">
                        {/* 🖱️ Step-by-Step Navigation */}
                        <div className="bg-white dark:bg-slate-900 rounded-3xl p-8 border border-slate-100 dark:border-slate-800 shadow-lg">
                          <div className="flex items-center gap-2 text-[#217346] dark:text-green-500 font-bold text-xs uppercase tracking-widest mb-6">
                            <MousePointer2 className="w-4 h-4" />
                            Step-by-Step Navigation
                          </div>
                          <ul className="space-y-4">
                            {solution.navigationSteps.map((step, i) => (
                              <li key={i} className="flex gap-4 items-start group">
                                <span className="w-6 h-6 rounded-lg bg-slate-100 dark:bg-slate-800 flex items-center justify-center text-xs font-bold text-slate-400 dark:text-slate-500 group-hover:bg-[#217346] dark:group-hover:bg-[#28a162] group-hover:text-white transition-colors">
                                  {i + 1}
                                </span>
                                <span className="text-slate-600 dark:text-slate-300 font-medium leading-relaxed group-hover:text-slate-900 dark:group-hover:text-white transition-colors">{step}</span>
                              </li>
                            ))}
                          </ul>
                        </div>

                        {/* ⌨️ Shortcuts */}
                        <div className="bg-slate-900 rounded-3xl p-8 text-white shadow-2xl relative overflow-hidden group">
                          <div className="absolute top-0 right-0 p-8 opacity-10 group-hover:opacity-20 transition-opacity">
                            <Keyboard className="w-24 h-24" />
                          </div>
                          <div className="relative z-10">
                            <div className="flex items-center gap-2 text-green-400 font-bold text-xs uppercase tracking-widest mb-8">
                              <Keyboard className="w-4 h-4" />
                              Shortcut Commands
                            </div>
                            <div className="space-y-8">
                              <div>
                                <p className="text-slate-400 text-[10px] uppercase font-bold tracking-widest mb-2">Windows</p>
                                <p className="text-2xl font-mono font-bold tracking-widest">{solution.shortcuts.windows}</p>
                              </div>
                              <div>
                                <p className="text-slate-400 text-[10px] uppercase font-bold tracking-widest mb-2">MacOS</p>
                                <p className="text-2xl font-mono font-bold tracking-widest">{solution.shortcuts.mac}</p>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>

                      {/* Breakdown and Visuals */}
                      <div className="grid md:grid-cols-[1.5fr_1fr] gap-8">
                        {/* Human Readable Logic */}
                        <div className="bg-white dark:bg-slate-900 rounded-3xl p-8 border border-slate-100 dark:border-slate-800 shadow-lg relative overflow-hidden">
                          <div className="absolute top-0 right-0 p-4 opacity-5 dark:opacity-10">
                             <History className="w-20 h-20" />
                          </div>
                          <div className="relative z-10 font-medium italic text-slate-600 dark:text-slate-300 border-l-4 border-[#217346] pl-6 py-2 text-lg leading-relaxed">
                            "{solution.humanReadableLogic}"
                          </div>
                        </div>

                        {/* 💡 Pro-Tip */}
                        <div className="bg-yellow-50 dark:bg-yellow-950/20 rounded-3xl p-8 border border-yellow-100 dark:border-yellow-900/50 shadow-sm transition-transform hover:scale-[1.02]">
                          <div className="flex items-center gap-2 text-yellow-700 dark:text-yellow-500 font-bold text-xs uppercase tracking-widest mb-4">
                            <Lightbulb className="w-4 h-4" />
                            Pro-Tip
                          </div>
                          <p className="text-yellow-900 dark:text-yellow-200 font-medium">
                            {solution.proTip}
                          </p>
                        </div>
                      </div>

                      {/* 📊 Visualization Architecture */}
                      {solution.visualization && (
                        <motion.div 
                          initial={{ opacity: 0, y: 30 }}
                          whileInView={{ opacity: 1, y: 0 }}
                          className="bg-white dark:bg-slate-900 rounded-3xl overflow-hidden border border-slate-100 dark:border-slate-800 shadow-xl"
                        >
                          <div className="bg-[#217346] px-8 py-4 flex items-center justify-between">
                            <div className="flex items-center gap-2 text-white font-bold text-xs uppercase tracking-widest">
                              <BarChart3 className="w-4 h-4" />
                              Visual Infrastructure
                            </div>
                            <button 
                              onClick={handleSaveTemplate}
                              className={`flex items-center gap-2 px-3 py-1 rounded-lg text-[10px] font-black uppercase tracking-widest transition-all ${saveStatus ? 'bg-green-500 text-white' : 'bg-white/10 text-white/80 hover:bg-white/20'}`}
                            >
                              {saveStatus ? <CheckCircle2 className="w-3 h-3" /> : <Bookmark className="w-3 h-3" />}
                              {saveStatus || 'Save as Template'}
                            </button>
                          </div>

                          <div className="p-8 space-y-8">
                            <div className="flex flex-col md:flex-row gap-8">
                              <div className="flex-1 space-y-6">
                                <div>
                                  <h4 className="text-2xl font-black text-slate-800 dark:text-white mb-2 leading-none">
                                    {solution.visualization.suggestedType}
                                  </h4>
                                  <p className="text-slate-500 dark:text-slate-400 font-medium leading-relaxed italic">
                                    {solution.visualization.why}
                                  </p>
                                </div>
                                
                                <div className="bg-yellow-50 dark:bg-yellow-950/20 border border-yellow-100 dark:border-yellow-900/50 rounded-2xl p-6">
                                  <div className="flex items-center gap-2 text-yellow-700 dark:text-yellow-500 font-bold text-[10px] uppercase tracking-widest mb-2">
                                    <Lightbulb className="w-4 h-4" />
                                    Aesthetic Engineering
                                  </div>
                                  <p className="text-yellow-900 dark:text-yellow-200 text-sm font-medium leading-relaxed">
                                    {solution.visualization.designTip}
                                  </p>
                                </div>
                              </div>

                              <div className="flex-1 bg-slate-50 dark:bg-slate-800 rounded-2xl p-6 border border-slate-100 dark:border-slate-700">
                                <div className="flex items-center gap-2 text-[#217346] dark:text-green-500 font-bold text-[10px] uppercase tracking-widest mb-4">
                                  <FileSpreadsheet className="w-4 h-4" />
                                  Data Setup Blueprint
                                </div>
                                <div className="text-slate-700 dark:text-slate-300 text-sm font-medium leading-relaxed space-y-3">
                                  {solution.visualization.setupGuidance.split('\n').map((line, i) => (
                                    <p key={i}>{line}</p>
                                  ))}
                                </div>
                              </div>
                            </div>
                          </div>
                        </motion.div>
                      )}

                      {/* History Drawer */}
                      <div className="mt-16 pt-16 border-t border-slate-200 dark:border-slate-800">
                        <div className="flex items-center gap-2 text-slate-400 font-bold text-xs uppercase tracking-widest mb-6">
                          <History className="w-4 h-4" />
                          Recent Architectural Blueprints
                        </div>
                        <div className="grid sm:grid-cols-2 md:grid-cols-3 gap-4">
                          {history.map((item, idx) => (
                            <button
                              key={idx}
                              onClick={() => setSolution(item)}
                              className={`text-left p-4 rounded-2xl border transition-all truncate hover:shadow-md ${solution.goal === item.goal ? 'bg-[#217346]/5 dark:bg-[#217346]/10 border-[#217346] text-[#217346] dark:text-green-500' : 'bg-white dark:bg-slate-900 border-slate-200 dark:border-slate-800 text-slate-500 hover:border-slate-300 dark:hover:border-slate-700 font-semibold text-sm'}`}
                            >
                              <p className="font-bold text-xs uppercase opacity-60 mb-1">Goal {history.length - idx}</p>
                              <p className="truncate">{item.goal}</p>
                            </button>
                          ))}
                        </div>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </main>

      <ModalOverlay isOpen={view === 'shortcuts'} onClose={() => setView('architect')}>
        <ShortcutGuide onClose={() => setView('architect')} />
      </ModalOverlay>

      <ModalOverlay isOpen={view === 'debugger'} onClose={() => setView('architect')}>
        <FormulaDebugger initialFormula={debugTarget} onClearInitial={() => setDebugTarget('')} onClose={() => setView('architect')} />
      </ModalOverlay>

      <ModalOverlay isOpen={view === 'templates'} onClose={() => setView('architect')}>
        <SavedTemplates onClose={() => setView('architect')} />
      </ModalOverlay>

      <ModalOverlay isOpen={view === 'formatting'} onClose={() => setView('architect')}>
        <FormattingGuide 
          onClose={() => setView('architect')}
          onDebug={(formula) => {
            setDebugTarget(formula);
            setView('debugger');
          }} 
        />
      </ModalOverlay>

      {/* Footer / Credits */}
      <footer className="text-center py-12 bg-white/50 dark:bg-slate-900/50 text-slate-400 dark:text-slate-500 text-xs uppercase tracking-[0.3em] font-medium border-t border-slate-100 dark:border-slate-800 transition-colors">
        Engineered by XL-Architect &bull; AI Powered Precision
      </footer>
    </div>
  );
}
